services:
  - type: web
    name: shopeasy-api
    runtime: node
    plan: free
    region: singapore
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: COOKIE_SECURE
        value: "true"
      - key: SEED_PRODUCTS
        value: "true"
      - key: ADMIN_NAME
        value: Admin
      - key: CURRENCY
        value: INR
      - key: SHIPPING_FEE
        value: "49"
      - key: FREE_SHIPPING_THRESHOLD
        value: "999"
      - key: BREVO_FROM_NAME
        value: ShopEasy
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: BREVO_API_KEY
        sync: false
      - key: BREVO_FROM_EMAIL
        sync: false
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
